### PR TITLE
procurement request's short_id

### PR DESCRIPTION
**Pull request by nimaai**
https://github.com/leihs/leihs/issues/915

ToDo:
- [x] request permission field spec
- [x] ON INSERT procurement_budget_periods also INSERT INTO procurement_requests_counters
- [x] ON DELETE procurement_budget_periods DELETE procurement_requests_counters (foreign key connection)
- [x] constraint on `procurement_budget_periods.name`(allowed chars)

### CODE REVIEW

**Comment by eins78** [comment]
@nimaai API queries and UI is done.

**Comment by eins78** [comment]
@nimaai pull this https://github.com/leihs/leihs-procure/compare/mfa/procurement_short_id and I think you latest commit here can be removed (its not a "field" so no spec needed)

**Comment by nimaai** [comment]
Spec to be done:
```cucumber
When I create a new budget period "XY"
And I create a request in this budget period
Then the new request has short ID "XY-01"
When I delete the request
And I create a request in this budget period again
Then the new request has short ID "XY-01"
When I delete the new budget period
Then the respective counter has been deleted in the database
```

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e03ed9003f58ac8f4cb4f8f2305a9b1a5f5d7cf9

**Pull request closed without merging**
